name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: 'production'
      JAVA_OPTS: '-Xmx1024m'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn clean install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Test with Maven
        run: mvn test

  post:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Post action message
        run: echo 'This will always run'
